//! Registry of conditional hypotheses, generated by `build.rs` from `hypotheses/*/`.
//! Do not edit per hypothesis: each hypothesis lives entirely in its own directory.

include!(concat!(env!("OUT_DIR"), "/registry.rs"));
